package expensesDb;
// Generated Jan 7, 2014 5:40:32 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private Integer categoryId;
     private String name;
     private Set<Userscategories> userscategorieses = new HashSet<Userscategories>(0);
     private Set<Expenses> expenseses = new HashSet<Expenses>(0);

    public Categories() {
    }
	
    public Categories(String name) {
        this.name = name;
    }
    public Categories(String name, Set<Userscategories> userscategorieses, Set<Expenses> expenseses) {
       this.name = name;
       this.userscategorieses = userscategorieses;
       this.expenseses = expenseses;
    }
   
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Userscategories> getUserscategorieses() {
        return this.userscategorieses;
    }
    
    public void setUserscategorieses(Set<Userscategories> userscategorieses) {
        this.userscategorieses = userscategorieses;
    }
    public Set<Expenses> getExpenseses() {
        return this.expenseses;
    }
    
    public void setExpenseses(Set<Expenses> expenseses) {
        this.expenseses = expenseses;
    }
}