package expensesDb;
// Generated Jan 7, 2014 5:40:32 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * Expenses generated by hbm2java
 */
public class Expenses  implements java.io.Serializable {


     private Integer expenseId;
     private Categories categories;
     private Users users;
     private String description;
     private Date date;
     private BigDecimal price;

    public Expenses() {
    }

    public Expenses(Categories categories, Users users, String description, Date date, BigDecimal price) {
       this.categories = categories;
       this.users = users;
       this.description = description;
       this.date = date;
       this.price = price;
    }
   
    public Integer getExpenseId() {
        return this.expenseId;
    }
    
    public void setExpenseId(Integer expenseId) {
        this.expenseId = expenseId;
    }
    
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


