package expensesDb;
// Generated Jan 7, 2014 5:40:32 PM by Hibernate Tools 3.6.0



/**
 * UserscategoriesId generated by hbm2java
 */
public class UserscategoriesId  implements java.io.Serializable {


     private int userId;
     private int categoryId;

    public UserscategoriesId() {
    }

    public UserscategoriesId(int userId, int categoryId) {
       this.userId = userId;
       this.categoryId = categoryId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserscategoriesId) ) return false;
		 UserscategoriesId castOther = ( UserscategoriesId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getCategoryId()==castOther.getCategoryId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getCategoryId();
         return result;
   }   


}


