package expensesDb;
// Generated Jan 7, 2014 5:40:32 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String authCode;
     private String sessionKey;
     private Set<Userscategories> userscategorieses = new HashSet<Userscategories>(0);
     private Set<Expenses> expenseses = new HashSet<Expenses>(0);

    public Users() {
    }

	
    public Users(String username, String authCode) {
        this.username = username;
        this.authCode = authCode;
    }
    public Users(String username, String authCode, String sessionKey, Set<Userscategories> userscategorieses, Set<Expenses> expenseses) {
       this.username = username;
       this.authCode = authCode;
       this.sessionKey = sessionKey;
       this.userscategorieses = userscategorieses;
       this.expenseses = expenseses;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getAuthCode() {
        return this.authCode;
    }
    
    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }
    public String getSessionKey() {
        return this.sessionKey;
    }
    
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
    }
    public Set<Userscategories> getUserscategorieses() {
        return this.userscategorieses;
    }
    
    public void setUserscategorieses(Set<Userscategories> userscategorieses) {
        this.userscategorieses = userscategorieses;
    }
    public Set<Expenses> getExpenseses() {
        return this.expenseses;
    }
    
    public void setExpenseses(Set<Expenses> expenseses) {
        this.expenseses = expenseses;
    }




}


